#!/usr/bin/env bash

# gorun simulates running `go run .` by creating a tempoarary binary
# and also listens for interrupts, Go program termination, or file changes,
# restarting the Go program if any file changes are detected.

# PID for the active instance of the Go program
app_pid=""
VERSION="v1.0.0"

# running go-run without args targets the current directory
if [[ -z "$1" ]]; then
  target_dir="."
else
  target_dir="$1"
fi


help() {
    echo "Usage: go-run [target]|version|update|help"
    echo
    echo "  [target]:   name the directory containing Go program to run"
    echo "  version:    print the version of go-run"
    echo "  update:     update go-run to the latest version"
    echo "  help:       print this help message"
    echo
    exit 0
}

version() {
  echo "go-run $VERSION"
}

update() {
  version
  echo "Updating go-run..."
  if ! curl -s https://raw.githubusercontent.com/grackleclub/go-run/main/go-run > "$0"; then
    echo "Failed to update go-run"
    return 1
  fi
  chmod +x "$0"
  echo "go-run updated"
  version
  return 0
}

# help
if [[ "$1" == "-h" || "$1" == "--help" || "$1" == "help" ]]; then
  help
fi

# version
if [[ "$1" == "-v" || "$1" == "--version" || "$1" == "version" ]]; then
    echo "go-run $VERSION"
    exit 0
fi

## update
if [[ "$1" == "update" ]]; then
  if ! update; then
    exit 1
  fi
  exit 0
fi


# separate output from this script from the Go program
# by providing a terminal-wide line break with sytlized text
line_break() {
  local title
  title=$(printf " %s %s %s " "$1" "$0" $VERSION "$1")
  local width
  width=$(tput cols)
  local title_length=$(( ${#title} + 2 ))
  local fill_length=$(( (width - title_length) / 2 ))
  printf '%*s' "$fill_length" '' | tr ' ' '-'
  printf '%s' "$title"
  printf '%*s\n' "$fill_length" '' | tr ' ' '-'
}

# use time of last save and list of all files to detect changes
state() {
  find ./* -type f -not -name "temp" -exec stat -c "%Y %n" {} \;
}

# run the Go program with passed arguments
run_go_app() {
  exists=$(pgrep temp)
  if [[ -n $exists ]]; then
    printf "🪓 Killing running Go program..."
    if ! pkill temp; then
      printf "failed. 🤷\n"
      return 1
    fi
    printf "dead. 💀\n"
  fi

  echo "🏗️  Binary is building..."
  # This is a binary not a 'go run' because it seems that
  # go run creates a temporary binary and then runs it,
  # so we can't capture the PID of the running process.
  #
  # Instead, we simulate go run with our own temp binary.
  if ! go build -o temp "$target_dir"; then
    echo "❌ Binary build failed for target directory: \"$target_dir\""
    exit 1
  fi
  echo "✅ Binary is built!"

  # listen for a SIGINT (ctrl-c) and cancel when received
  trap 'echo; 
    line_break 🚧;
    printf "⛔ Cancelling...\n";
    pkill temp & exit;' INT

  # cleanup temp binary on exit, regardless of cause
  trap 'printf "🚮 Cleaning up temp binary on exit...";
    rm -f temp;
    printf "bye!\n"' EXIT

  echo "🚀 Starting Go app and watching for changes... 👀"
  line_break 🚧

  # echo the command being run
  if [[ -z "$*" ]]; then
    printf "go run .\n"
  else
    printf "go run %s\n" "$*"
  fi
  ./temp "$@" &
  app_pid=$!
}

# exit if the app has terminated, passing along exit code
exit_if_done() {
  if ! kill -0 $app_pid 2>/dev/null; then
    wait $app_pid
    exit_code=$?
    line_break 🚧
    echo "🚫 Go app terminated ($exit_code) exiting..."
    exit "$exit_code"
  fi
  return 0
}

# line breaks help differentiate go-run output from application output
line_break 🚧 

# require Go
if ! go_version=$(go version); then
  echo "🧐 Go is not installed or missing from PATH."
  echo "Install go and try again:"
  echo "  https://go.dev"
  echo
  exit 1
else
  echo "🐹 $go_version"
fi

# initial run before listening for any changes
state_old=$(state)
run_go_app "$@"

# continue to watch for changes, restarting or exiting as appropriate
while true; do
  sleep 1
  exit_if_done


  state_new=$(state)
  if [[ "$state_old" != "$state_new" ]]; then
    line_break 🚧
    echo "🔄 File change detected!"

	diff <(echo "$state_old") <(echo "$state_new") | grep -E '^<|>'

    run_go_app "$@"
    state_old=$state_new
  fi
done
