name: Shellcheck

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - go-run

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Shellcheck
      run: shellcheck go-run
