name: Update Version

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update go-run version
      run: ./update-version

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: main
        commit_message: bump version
